sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov

script:
  - python -m pytest --cov=numerapi

after_success:
  - codecov
